### ISSUE TITLE
[Problems compiling with conan] (Version: [1.10.0])

### ISSUE THREAD

**Issue by nmiceli-simtlix** [XRPLF/rippled#4465]
## Issue Description
This document is pretty generic and not so friendly to follow. This is a big change, specially when you are supposed to update for a protocol change.
https://github.com/XRPLF/rippled/blob/develop/BUILD.md

## Steps to Reproduce
The error happens on the last step:

conan export external/snappy snappy/1.1.9@
mkdir .build
cd .build
conan install .. --output-folder . --build missing --settings build_type=Release
cmake -DCMAKE_TOOLCHAIN_FILE:FILEPATH=build/generators/conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release ..
cmake --build .

## Expected Result
A compiled binary

## Actual Result
[  9%] Building CXX object CMakeFiles/xrpl_core.dir/src/ripple/protocol/impl/AccountID.cpp.o
In file included from /build/ripple/binary/src/ripple/basics/base_uint.h:28,
                 from /build/ripple/binary/src/ripple/protocol/AccountID.h:27,
                 from /build/ripple/binary/src/ripple/protocol/impl/AccountID.cpp:22:
/build/ripple/binary/src/ripple/basics/Expected.h:139:5: error: 'requires' does not name a type
  139 |     requires std::convertible_to<U, T> constexpr Expected(U && r)
      |     ^~~~~~~~
/build/ripple/binary/src/ripple/basics/Expected.h:140:37: error: expected unqualified-id before ')' token
  140 |         : Base(T{std::forward<U>(r)})
      |                                     ^
/build/ripple/binary/src/ripple/basics/Expected.h:145:9: error: 'requires' does not name a type
  145 |         requires std::convertible_to<U, E> &&
      |         ^~~~~~~~
/build/ripple/binary/src/ripple/basics/Expected.h:147:39: error: expected unqualified-id before ')' token
  147 |         : Base(E{std::move(e.value())})
      |                                       ^
/build/ripple/binary/src/ripple/basics/Expected.h:221:9: error: 'requires' does not name a type
  221 |         requires std::convertible_to<U, E> &&
      |         ^~~~~~~~
/build/ripple/binary/src/ripple/basics/Expected.h:223:39: error: expected unqualified-id before ')' token
  223 |         : Base(E{std::move(e.value())})
      |                                       ^
In file included from /build/ripple/binary/src/ripple/protocol/AccountID.h:27,
                 from /build/ripple/binary/src/ripple/protocol/impl/AccountID.cpp:22:
/build/ripple/binary/src/ripple/basics/base_uint.h: In instantiation of 'constexpr ripple::Expected<decltype (((ripple::base_uint<Bits, Tag>*)(void)0)->ripple::base_uint<Bits, Tag>::data_), ripple::base_uint<Bits, Tag>::ParseResult> ripple::base_uint<Bits, Tag>::parseFromStringView(std::string_view) [with long unsigned int Bits = 160; Tag = ripple::detail::AccountIDTag; decltype (((ripple::base_uint<Bits, Tag>*)(void)0)->ripple::base_uint<Bits, Tag>::data_) = std::array<unsigned int, 5>; std::string_view = std::basic_string_view<char>]':
/build/ripple/binary/src/ripple/basics/base_uint.h:497:20:   required from 'constexpr bool ripple::base_uint<Bits, Tag>::parseHex(std::string_view) [with long unsigned int Bits = 160; Tag = ripple::detail::AccountIDTag; std::string_view = std::basic_string_view<char>]'
/build/ripple/binary/src/ripple/basics/base_uint.h:514:46:   required from 'bool ripple::base_uint<Bits, Tag>::parseHex(const string&) [with long unsigned int Bits = 160; Tag = ripple::detail::AccountIDTag; std::string = std::basic_string<char>]'
/build/ripple/binary/src/ripple/protocol/impl/AccountID.cpp:184:26:   required from here
/build/ripple/binary/src/ripple/basics/base_uint.h:226:20: error: could not convert 'ret' from 'std::array<unsigned int, 5>' to 'ripple::Expected<std::array<unsigned int, 5>, ripple::base_uint<160, ripple::detail::AccountIDTag>::ParseResult>'
  226 |             return ret;
      |                    ^~~
      |                    |
      |                    std::array<unsigned int, 5>
/build/ripple/binary/src/ripple/basics/base_uint.h:230:53: error: could not convert 'ripple::Unexpected<ripple::base_uint<160, ripple::detail::AccountIDTag>::ParseResult>(ripple::base_uint<160, ripple::detail::AccountIDTag>::ParseResult::badLength)' from 'ripple::Unexpected<ripple::base_uint<160, ripple::detail::AccountIDTag>::ParseResult>' to 'ripple::Expected<std::array<unsigned int, 5>, ripple::base_uint<160, ripple::detail::AccountIDTag>::ParseResult>'
  230 |             return Unexpected(ParseResult::badLength);
      |                                                     ^
      |                                                     |
      |                                                     ripple::Unexpected<ripple::base_uint<160, ripple::detail::AccountIDTag>::ParseResult>
/build/ripple/binary/src/ripple/basics/base_uint.h:241:45: error: could not convert 'ripple::Unexpected<ripple::base_uint<160, ripple::detail::AccountIDTag>::ParseResult>(result)' from 'ripple::Unexpected<ripple::base_uint<160, ripple::detail::AccountIDTag>::ParseResult>' to 'ripple::Expected<std::array<unsigned int, 5>, ripple::base_uint<160, ripple::detail::AccountIDTag>::ParseResult>'
  241 |                     return Unexpected(result);
      |                                             ^
      |                                             |
      |                                             ripple::Unexpected<ripple::base_uint<160, ripple::detail::AccountIDTag>::ParseResult>
/build/ripple/binary/src/ripple/basics/base_uint.h:245:16: error: could not convert 'ret' from 'std::array<unsigned int, 5>' to 'ripple::Expected<std::array<unsigned int, 5>, ripple::base_uint<160, ripple::detail::AccountIDTag>::ParseResult>'
  245 |         return ret;
      |                ^~~
      |                |
      |                std::array<unsigned int, 5>
make[2]: *** [CMakeFiles/xrpl_core.dir/build.make:492: CMakeFiles/xrpl_core.dir/src/ripple/protocol/impl/AccountID.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:209: CMakeFiles/xrpl_core.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

## Environment

Ubuntu 20.04
Python3 - 3.8.2
Conan - 1.59.0 (Conan 2.0.2 is a totally different version and doesn't work)
Build-essential - 12.8ubuntu1.1

**Comment by dangell7** [comment]
@nmiceli-simtlix What version of boost?

Also can you try conan 1.55? I believe that is the version that needs to be used.

**Comment by nmiceli-simtlix** [comment]
Found my problem. Here's what was wrong: 
Ubuntu 20.04 installs gcc-9 and g++-9 by default. After installing gcc-10 g++-10 and cpp-10, you need to run the following:

update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 --slave /usr/bin/g++ g++ /usr/bin/g++-10 --slave /usr/bin/gcov gcov /usr/bin/gcov-10

If not, conan will default to version 9.

BTW, I was able to build with conan 1.59.0 and boost 1.75.0

**Comment by intelliot** [comment]
@nmiceli-simtlix: Could you add that information to BUILD.md and open a PR?

**Comment by thejohnfreeman** [comment]
There are already instructions for this in `BUILD.md`. See "if you have multiple compilers installed" under [Prerequisites](https://github.com/XRPLF/rippled/blob/develop/BUILD.md#prerequisites).

**Comment by intelliot** [comment]
@nmiceli-simtlix @dangell7 if you have any suggestions for BUILD.md, please open a PR. Thanks!
